version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "8080:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=hxapi"
      depends_on:
        - db
      command: bash -c "php novice migrate && php novice seed && /usr/bin/supervisord"
  db:
      build:
          context: ./database
      ports:
          - 3306:3306
      environment:
          - MYSQL_DATABASE=hxapi
          - MYSQL_USER=slim
          - MYSQL_PASSWORD=slim
          - MYSQL_ROOT_PASSWORD=root
      volumes:
          - ./database/instance:/var/lib/mysql
