version: "2"
services:
  nginx:
      image: paradiddley/hxapi-nginx
      ports:
          - "8080:80"
      volumes:
          - ./app:/var/app
  fpm:
      image: paradiddley/hxapi-fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=hxapi"
      command: bash -c "/usr/bin/supervisord && php novice migrate && php novice seed"
  db:
      image: paradiddley/hxapi-db
      ports:
          - 3306:3306
      environment:
          - MYSQL_DATABASE=hxapi
          - MYSQL_USER=slim
          - MYSQL_PASSWORD=slim
          - MYSQL_ROOT_PASSWORD=root
      volumes:
          - ./database/instance:/var/lib/mysql
